### ISSUE TITLE
An error occured when minting your NFT. Error: Request failed with status code 500

### ISSUE THREAD

**Issue by Z-zzim** [RootSoft/algorand-php#1]
Hi!
I run IPFS Desktop and status - connected to IPFS.
I have some work addresses:

```
GATEWAY:  http://127.0.0.1:8080
API:  /ip4/127.0.0.1/tcp/5001
```

```
ADDRESSES:
/ip4/127.0.0.1/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/188.164.164.240/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/188.164.164.240/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/192.168.1.30/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/192.168.1.30/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip6/::1/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip6/::1/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
```
But in Chrome Console a completely different address (status code 500) when i try to create an item:
`POST http://192.168.1.190:81/asa/transaction/fields 500 (Internal Server Error)`
`{message: "cURL error 6: Could not resolve host: host.docker.…/host.docker.internal:5001/api/v0/add?only-hash=1", exception: "Rootsoft\\IPFS\\Exceptions\\IPFSException", file: "/var/www/html/vendor/rootsoft/laravel-ipfs/src/Traits/MakesHttpRequests.php", line: 93, trace: Array(50)}`

How should I change the address "host.docker.internal"? I tried to change to 127.0.0.1, but I get 500.
![issue01](https://user-images.githubusercontent.com/46194513/126004486-8151114a-7c45-4360-be34-be40b19e3322.jpg)
![issue02](https://user-images.githubusercontent.com/46194513/126004513-11d915aa-4347-4d07-8874-55c43b873692.jpg)

**Comment by RootSoft** [comment]
see https://github.com/RootSoft/algoland/issues/2#issuecomment-884777301
