### ISSUE TITLE
Transactions are not using mainnet credentials.

### ISSUE THREAD

**Issue by vipeeerr** [RootSoft/algorand-php#9]
When configuring Algorand.php with PureStake credentials for Mainnet the transactions are still done in TestNet.

When trying to hardcode the credentials in the rest of the package code, the actions on the Algorand network throw a 'Forbidden' error. 

Did I miss any settings?

**Comment by RootSoft** [comment]
I have tested this recently and wasn't able to reproduce it.
Is it possible to create a minimal, reproducable example that I can test with?

**Comment by vipeeerr** [comment]
I would have to build a new project to test and get it up on a LAMP. 🤔.

Just to confirm:

I install the package with composer.
I publish the configs of your package.
I add my keys to the config.file that was generated, directly or via .env
Php artisan optimize or php artisan config:cache

And that should be it, or am I skipping a process?
